### PR TITLE
Design mods

### PR DESCRIPTION
**Pull request by christopherhein**
I just started using WiFiSMS today, and fell in love so first off AMAZING JOB! really pumped about not having to use my phone all day while at work, My only complaint was the design/typography... Don't get me wrong Futura, and Gill Sans are great typefaces, but for text messages they don't really fit, as well I wasn't so hot for the super sized text... Last the placement of a few elements such as the status broke when the browser was scaled down. So I've made some design and layout changes, and modeled the design on the Beta Version of `Messages` for mac which was based on Messages for iPad overall I cleared out a bunch of heavy box shadows added a new background image and removed the super sized contact avatar next to the name... see screenshots below...

I'm 100% open for feedback, and would love to see this get into the actual repo on Cydia, Please let me know all your comments and concerns. 

Wide Screen

Small Screen

My next goal is to start working on prettier fancybox implementation and maybe a couple tweets to the "Send message bar", oh and make selecting emoji a little prettier...

### CODE REVIEW

**Comment by christopherhein** [comment]
I just noticed a problem with this where when viewed from the browser because I was using a linked image in the css it didn't actually work correct, so I base 64 encoded it locally will update my request later tonight.

**Comment by christopherhein** [comment]
Alright so now it's using a base 64 encoded image for the background so that it works. Let me know if you have any questions...

**Comment by shrmnk** [comment]
It's looking good! Could the 3 buttons on the left of the compose box be smaller especially when the window size gets small?

**Comment by chid** [comment]
Hey Chris, did you get your changed pulled in?

**Comment by christopherhein** [comment]
@chid nope

**Pull request closed without merging**
