### PR TITLE
iPhone3G support

### PR DESCRIPTION
**Pull request by fopina**
Added armv6 to ARCHS to support iPhone 3G (#30 and #36)

### CODE REVIEW

**Comment by agent007se** [comment]
I really need this feature and I hope that this pull request will be accepted because there are still many people with an iPhone 3G !

**Comment by dryder** [comment]
I just downloaded the newest version (1.1.0) on my iPhone 3G with iOS 4.2.1 and I am getting the same problem. Cannot connect in the browser. I tried installing on my friend's iPhone 4 with iOS 5.1.1 and it works fine. Whats going on? I thought you added iPhone 3G support?

**Comment by fopina** [comment]
I pushed it, it was not merged by the owner of wifisms.

Sent from my phone

On 20/07/2012, at 05:58, dryder
reply@reply.github.com
wrote:

**Comment by dryder** [comment]
Sorry to sound completely stupid, but I'm new here. What does that mean exactly? lol

**Comment by fopina** [comment]
It means my change is not part of treason's (original) WifiSMS github repository which is the one in cydia

**Pull request closed without merging**
