### PR TITLE
Phone Number String Fix

### PR DESCRIPTION
**Pull request by jasonchutko**
Fixed an issue where not all improper characters are removed from phone numbers.

My first commit ^_^

### CODE REVIEW

**Comment by jasonchutko** [comment]
Sorry for the mess I caused :P, I've never done a Pull Request before. Commit 8bc614b should be working now.

**Comment by treason** [comment]
Nice work thanks! its funny because you are one step ahead. I was just gonna add that code along with a new message sending routine. 1.0.5 is on the way!

**Comment by treason** [comment]
would u try 1.0.5 for me? https://github.com/treason/WifiSMS/blob/master/Build/deb/WifiSMS-NOSBS-1.0.5.deb?raw=true

**Comment by jasonchutko** [comment]
Alright, I think I can confirm this fixed.  Loaded up my own AddressBook.sqlite that I believe was malformed, and the 1.0.5 worked fine.  Previous claims of breaking my phone were false :P

**Comment by treason** [comment]
Lol great. Thanks for testing

**Pull request closed without merging**
